from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib import colors
import os

def generate_session_report(session_obj, output_path):
    c = canvas.Canvas(output_path, pagesize=letter)
    width, height = letter

    # Header
    c.setFont("Helvetica-Bold", 24)
    c.setFillcolor(colors.HexColor("#6366f1"))
    c.drawString(1*inch, height - 1*inch, "BrainCoach AI - Performance Report")
    
    c.setFont("Helvetica", 12)
    c.setFillcolor(colors.black)
    c.drawString(1*inch, height - 1.5*inch, f"Child Name: {session_obj.child.name}")
    c.drawString(1*inch, height - 1.7*inch, f"Exercise: {session_obj.exercise.title}")
    c.drawString(1*inch, height - 1.9*inch, f"Date: {session_obj.start_time.strftime('%Y-%m-%d %H:%M')}")

    # Stats Box
    c.rect(1*inch, height - 3.5*inch, 6*inch, 1*inch, fill=0)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(1.2*inch, height - 2.8*inch, "Session Summary")
    
    c.setFont("Helvetica", 12)
    c.drawString(1.2*inch, height - 3.1*inch, f"Average Accuracy: {session_obj.avg_accuracy:.2f}%")
    c.drawString(1.2*inch, height - 3.3*inch, f"Total Score: {session_obj.total_score}")

    # AI Recommendation
    c.setFont("Helvetica-Bold", 14)
    c.drawString(1*inch, height - 4.2*inch, "AI Recommendation")
    
    c.setFont("Helvetica", 11)
    recommendation = (
        "Based on the hand tracking data, the concentration levels are improving. "
        "We recommend continuing with 'Finger Yoga' for another 3 sessions to solidify "
        "fine motor control before moving to the next level."
    )
    # Simple word wrap placeholder
    c.drawString(1*inch, height - 4.5*inch, recommendation[:80])
    c.drawString(1*inch, height - 4.7*inch, recommendation[80:])

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(1*inch, 0.5*inch, "Generated by BrainCoach AI - Empowering Kids through Technology")

    c.showPage()
    c.save()
    return output_path
